### ISSUE TITLE
question

### ISSUE THREAD

**Issue by how-to-do-frontend** [rushiiMachine/osu-patcher#1]
how do i make my own patches ? i wanna make a few of my own patches but i dont exactly understand this random array of code, can you help me?

**Comment by rushiiMachine** [comment]
My patch signatures are based on bytecode from the osu exe, viewable with a decompiler/disassembler like dnSpy (or it's forks)
I also use a deobfuscated variant of an older version of osu (the eazobfuscator key was leaked, multiple times) as a reference to make searching for code easier. If you know who to ask you can find it.
