### ISSUE TITLE
Can You give me your discord

### ISSUE THREAD

**Issue by takumoyoshi** [rushiiMachine/osu-patcher#15]
Im writing my osu switcher and I'm using your patcher, I would like to discuss cooperation with you. I'm leaving a link to your patcher, but I don't know how you feel about it!

**Comment by rushiiMachine** [comment]
you can ask anything here

**Comment by takumoyoshi** [comment]
But I already found your discord, maybe we'll talk there?

**Comment by takumoyoshi** [comment]
> you can ask anything here
But if you want to stay here - okay, no problem

**Comment by rushiiMachine** [comment]
my discord is for personal use

**Comment by takumoyoshi** [comment]
> my discord is for personal use

Ok, I see. So I'm writing Okayu Loader (https://github.com/takumoyoshi/OkayuLoader) on C# winui3. It's a tool that runs osu with devserver flag, I think it's better to have one program rather then have a thousands of lnk for every server. In future I will code a function, that runs osu with auto logged in account that user choosed (when you are switching between servers osu don't remember Your account and password). I also added feature that runs osu with your patcher. I don't know what should I do. I already added link to your patcher repo, but I also added compiled patcher in releases. I don't want to make thing when user must compile your patcher by himself, but I don't think that pin your patchee to releases is a good idea, because users will not go your repo and see who made patcher. What should I do? 
P.S. Im sorry about my English skills. Im from Russia and time in Moscow is 2:48 am, I'm not thinking straight anymore

**Comment by rushiiMachine** [comment]
no worries

> when you are switching between servers osu don't remember Your account and password

I have a tool for that, it's [pinned on my profile](https://github.com/rushiiMachine/osu-switcher) if you want to take a look.

You can include my project in a releases as long as you use the same license and give proper credit

![image](https://github.com/rushiiMachine/osu-patcher/assets/33725716/187ae39c-32be-44a3-a49e-7ae44afca3e3)

A hyperlink to this repository in the description of this button would suffice

**Comment by takumoyoshi** [comment]
Thank you very much! I will include patcher in releases but I will make hyperlink to you repo in patcher card. Thank you!

**Comment by rushiiMachine** [comment]
Also, I strongly urge against this

> Download the latest .msix installer from [Release page](https://github.com/takumoyoshi/OkayuLoader/releases) and then [trust OkayuLoader certificate](https://youtu.be/qMpVhnUN2g4). Download Patcher.7z and extract it in osu! folder.

Not only could you accidentally overwrite game files, it clutters your game directory and makes it unmanagable.
Also, just avoid msix, it's a pain in the ass. I don't like trusting random certificates and I doubt others would either. Just build a standalone version that doesn't require any installation.

**Comment by takumoyoshi** [comment]
Okay... So I will see how can I make a standalone version of winui3 apps... And I also change path to patcher from osu! folder to (for example) user documents or home directory

**Comment by blackwolf660** [comment]
@rushiiMachine is it possible to use the compiled version for auto-installation for Okayu Loader (https://github.com/takumoyoshi/OkayuLoader)?

**Comment by rushiiMachine** [comment]
as long as it complies with the aforementioned terms
